### ISSUE TITLE
None of the demos work as local web servers or online

### ISSUE THREAD

**Issue by everythingability** [ml4a/ml4a-demos#5]

**Comment by genekogan** [comment]
i just checked and they are confirmed working fine for me. if you can please be more specific about the error you are seeing, please let me know, as your blank message is very unhelpful.

**Comment by everythingability** [comment]
On this page (http://ml4a.github.io/demos/_, try this link (and others)
http://ml4a.github.io/dev/demos/demo_forwardpass.html 

None work

Download the repos, ran a python server and sites didn't do much... Lots of 404s...

Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [10/Sep/2018 19:01:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:05] "GET /css/main.css HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:05] code 404, message File not found
127.0.0.1 - - [10/Sep/2018 19:01:05] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [10/Sep/2018 19:01:10] "GET /examples/pitch-generative HTTP/1.1" 301 -
127.0.0.1 - - [10/Sep/2018 19:01:10] "GET /examples/pitch-generative/ HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:10] "GET /examples/pitch-generative/sketch.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:20] "GET /examples/facetrack-knn HTTP/1.1" 301 -
127.0.0.1 - - [10/Sep/2018 19:01:20] "GET /examples/facetrack-knn/ HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:20] "GET /examples/facetrack-knn/libs/knn.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:20] "GET /examples/facetrack-knn/libs/clmtrackr.min.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:20] "GET /examples/facetrack-knn/libs/model_pca_20_svm.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:20] "GET /examples/facetrack-knn/sketch.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:21] code 404, message File not found
127.0.0.1 - - [10/Sep/2018 19:01:21] "GET /examples/facetrack-knn/attribute%20vec2%20a_texCoord;attribute%20vec2%20a_position;varying%20vec2%20v_texCoord;void%20main()%20%7B%20%20%20//%20transform%20coordinates%20to%20regular%20coordinates%20%20%20gl_Position%20=%20vec4(a_position,0.0,1.0);%20%20%20%20//%20pass%20the%20texCoord%20to%20the%20fragment%20shader%20%20%20v_texCoord%20=%20a_texCoord;%7D HTTP/1.1" 404 -
127.0.0.1 - - [10/Sep/2018 19:01:21] code 404, message File not found
127.0.0.1 - - [10/Sep/2018 19:01:21] "GET /examples/facetrack-knn/[object%20WebGLRenderingContext] HTTP/1.1" 404 -
127.0.0.1 - - [10/Sep/2018 19:01:21] code 404, message File not found
127.0.0.1 - - [10/Sep/2018 19:01:21] "GET /examples/facetrack-knn/precision%20mediump%20float;uniform%20vec2%20u_onePixelPatches;//%20our%20patchesuniform%20sampler2D%20u_patches;//%20the%20texCoords%20passed%20in%20from%20the%20vertex%20shader.varying%20vec2%20v_texCoord;void%20main()%20%7B%20%20vec4%20bottomLeft%20=%20texture2D(u_patches,%20v_texCoord%20+%20vec2(-0.04762,%200.00265));%20%20vec4%20bottomRight%20=%20texture2D(u_patches,%20v_texCoord%20+%20vec2(0.04762,%200.00265));%20%20vec4%20topLeft%20=%20texture2D(u_patches,%20v_texCoord%20+%20vec2(-0.04762,%20-0.00265));%20%20vec4%20topRight%20=%20texture2D(u_patches,%20v_texCoord%20+%20vec2(0.04762,%20-0.00265));%20%20vec4%20dx%20=%20(%20%20%20%20bottomLeft%20+%20%20%20%20(texture2D(u_patches,%20v_texCoord%20+%20vec2(-0.04762,%200.0))*vec4(2.0,2.0,2.0,2.0))%20+%20%20%20%20topLeft%20-%20%20%20%20bottomRight%20-%20%20%20%20(texture2D(u_patches,%20v_texCoord%20+%20vec2(0.04762,%200.0))*vec4(2.0,2.0,2.0,2.0))%20-%20%20%20%20topRight)/4.0;%20%20vec4%20dy%20=%20(%20%20%20%20bottomLeft%20+%20%20%20%20(texture2D(u_patches,%20v_texCoord%20+%20vec2(0.0,%200.00265))*vec4(2.0,2.0,2.0,2.0))%20+%20%20%20%20bottomRight%20-%20%20%20%20topLeft%20-%20%20%20%20(texture2D(u_patches,%20v_texCoord%20+%20vec2(0.0,%20-0.00265))*vec4(2.0,2.0,2.0,2.0))%20-%20%20%20%20topRight)/4.0;%20%20vec4%20gradient%20=%20sqrt((dx*dx)%20+%20(dy*dy));%20%20gl_FragColor%20=%20gradient;%7D HTTP/1.1" 404 -
127.0.0.1 - - [10/Sep/2018 19:01:21] code 404, message File not found
127.0.0.1 - - [10/Sep/2018 19:01:21] "GET /examples/facetrack-knn/[object%20WebGLRenderingContext] HTTP/1.1" 404 -
127.0.0.1 - - [10/Sep/2018 19:01:28] "GET /examples/regression-simple HTTP/1.1" 301 -
127.0.0.1 - - [10/Sep/2018 19:01:28] "GET /examples/regression-simple/ HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:28] "GET /examples/regression-simple/sketch.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:53] "GET /examples/posenet-simple HTTP/1.1" 301 -
127.0.0.1 - - [10/Sep/2018 19:01:53] "GET /examples/posenet-simple/ HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:01:53] "GET /examples/posenet-simple/sketch.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:03:13] "GET /examples/posenet-sound HTTP/1.1" 301 -
127.0.0.1 - - [10/Sep/2018 19:03:13] "GET /examples/posenet-sound/ HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:03:13] "GET /examples/posenet-sound/sketch.js HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:03:20] "GET /examples/classification-simple HTTP/1.1" 301 -
127.0.0.1 - - [10/Sep/2018 19:03:20] "GET /examples/classification-simple/ HTTP/1.1" 200 -
127.0.0.1 - - [10/Sep/2018 19:03:20] "GET /examples/classification-simple/sketch.js HTTP/1.1" 200 -

**Comment by genekogan** [comment]
you are probably launching the server from the wrong location. you need to do it from root. look at the paths: /examples/...   this assumes ml4a-demos is the root folder of the server.

**Comment by everythingability** [comment]
Aha... they work better now thanks
